"""
AI Teaching Assistant API routes for EduVision AI.
Provides alert monitoring, alert acknowledgement, and real-time
pedagogical recommendations (Gemini 1.5 Flash + Offline fallback).
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session as DBSession

from src.database.connection import get_db
from src.ai_assistant.alerts import AlertRuleEngine
from src.ai_assistant.assistant import TeachingAssistant
from src.api.routes.engagement import get_live_engagement

router = APIRouter()

alert_engine = AlertRuleEngine(cooldown_seconds=45.0)
teaching_assistant = TeachingAssistant()


class AcknowledgeResponse(BaseModel):
    status: str
    alert_id: int
    acknowledged: bool


class RecommendationRequest(BaseModel):
    subject: Optional[str] = "Engineering & Computer Science Lecture"
    duration_minutes: Optional[int] = 30


@router.get("/status")
def get_assistant_status():
    """Returns AI Teaching Assistant configuration, model source, and active alert stats."""
    is_gemini = teaching_assistant.is_gemini_active()
    recent = alert_engine.get_recent_alerts(limit=50, unacknowledged_only=True)
    return {
        "status": "active",
        "gemini_configured": is_gemini,
        "active_model": "Gemini 1.5 Flash" if is_gemini else "EduVision Offline Pedagogical Engine",
        "unacknowledged_alerts_count": len(recent),
        "alert_cooldown_seconds": alert_engine.cooldown_seconds
    }


@router.get("/alerts")
def list_alerts(
    limit: int = Query(20, ge=1, le=100),
    unacknowledged_only: bool = Query(False)
):
    """Lists recent pedagogical alerts generated by the rule engine."""
    alerts = alert_engine.get_recent_alerts(limit=limit, unacknowledged_only=unacknowledged_only)
    return {
        "total": len(alerts),
        "alerts": alerts
    }


@router.post("/alerts/{alert_id}/acknowledge", response_model=AcknowledgeResponse)
def acknowledge_alert(alert_id: int):
    """Marks an alert as acknowledged by the teacher."""
    success = alert_engine.acknowledge_alert(alert_id)
    if not success:
        raise HTTPException(status_code=404, detail=f"Alert with ID {alert_id} not found")
    return {
        "status": "success",
        "alert_id": alert_id,
        "acknowledged": True
    }


@router.post("/recommend")
def get_recommendation(payload: Optional[RecommendationRequest] = None, db: DBSession = Depends(get_db)):
    """
    Captures current live classroom engagement telemetry and generates
    targeted pedagogical recommendations using Gemini 1.5 Flash / offline engine.
    """
    subject = payload.subject if payload else "Engineering Lecture"
    duration = payload.duration_minutes if payload else 30

    # Get live engagement snapshot
    live_data = get_live_engagement(session_id=None, db=db)
    cei = live_data.get("class_engagement_index", 100.0)
    students = live_data.get("students", [])
    active_alerts = live_data.get("active_alerts", [])

    # Evaluate rules to trigger any pending alerts into DB
    new_alerts = alert_engine.evaluate_classroom(
        class_engagement_index=cei,
        students_analysis=students,
        session_id=None
    )

    all_alerts = active_alerts + [a["message"] for a in new_alerts]

    # Generate recommendations
    rec = teaching_assistant.generate_recommendations(
        class_engagement_index=cei,
        students=students,
        active_alerts=all_alerts,
        subject=subject,
        duration_minutes=duration
    )

    return {
        "status": "success",
        "recommendation": rec,
        "newly_triggered_alerts": new_alerts,
        "timestamp": datetime.utcnow().isoformat()
    }
